#pragma once

#include "rend/core/result.h"
#include "rend/gpu/image.h"

#include <cstdint>
#include <memory>

typedef struct VkCommandPool_T* VkCommandPool;
typedef struct VkCommandBuffer_T* VkCommandBuffer;
typedef struct VkFence_T* VkFence;

namespace rend::gpu {

class Buffer;
class Device;

// Turns decoded RGBA8 pixels into sampled, mipmapped GPU textures. Runs on
// the graphics queue — mip generation blits, and transfer-only queues
// cannot blit. Synchronous per texture (load-time tool, not a streaming
// path; async texture residency is a renderer-layer concern later).
class TextureUploader {
public:
    static Result<std::unique_ptr<TextureUploader>> create(const Device& device);
    ~TextureUploader();

    TextureUploader(const TextureUploader&) = delete;
    TextureUploader& operator=(const TextureUploader&) = delete;

    // Full mip chain, generated by blits; sRGB format by default (base
    // color content). Pixels are tightly-packed RGBA8.
    Result<std::unique_ptr<Image>> upload(std::uint32_t width, std::uint32_t height,
                                          const void* rgba8, bool srgb = true);

private:
    TextureUploader() = default;
    Result<void> ensureStagingCapacity(std::uint64_t required);

    const Device* device_ = nullptr;
    VkCommandPool pool_ = nullptr;
    VkCommandBuffer cmd_ = nullptr;
    VkFence fence_ = nullptr;
    std::unique_ptr<Buffer> staging_;
};

} // namespace rend::gpu
